### ISSUE TITLE
Document that there is no route change watcher.

### ISSUE THREAD

**Issue by jwicks31** [paralleldrive/react-feature-toggles#175] opened 2018-08-06 14:44 UTC
Add documentation about `FeatureToggles` and supporting functions needing to be inside of routes so that it is re-run on route changes.

**Comment by kennylavender** [comment] 2018-08-06 17:07
@jwicks31 as I mentioned in the other issue, this is not an issue with react-feature-toggles. Its an issue with how it was used. So documentation at most, not a bug.

**Comment by kennylavender** [comment] 2019-03-09 22:49
Closing for now, I think the examples we will be adding should help with this.

**Closed by kennylavender** 2019-03-09 22:49 UTC
Labels: enhancement
